# Generated by Django 2.1.7 on 2019-03-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
